# Links and message board

friends:
  layout: flink
  title: 友情链接
  desc: 遇见你们很开心
  button:
    text: 申请友链
    url: /comments/

envelope_comment:
  enable: true
  custom_pic:
    cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png
  message:
    - 有什么想问的？
    - 有什么想说的？
    - 有什么想吐槽的？
    - 哪怕是有什么想吃的，都可以告诉我哦~
    - 遗憾的是，因为我没有挂评论系统，所以请当面联系我
    - 欸嘿~
  bottom: 自动书记人偶竭诚为您服务！
  height:
  path:
  front_matter:
    title: 留言板
    comments: true
