# Home-page extensions

swiper:
  enable: true
  priority: 5
  enable_page: /
  timemode: date
  layout:
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js

tag_plugins:
  enable: true
  priority: 5
  issues: false
  link:
    placeholder: /img/link.png
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js
    iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css

aplayerInject:
  enable: true
  per_page: true
